Repository jenkinsci/blueocean-maven-plugin, pull requests merged in 2021-06, with the labels that each got.

#19 Java 1.8 as mininum
  .github/workflows/maven.yml
  Jenkinsfile
  pom.xml
  src/main/java/io/jenkins/blueocean/maven/plugin/ProcessUpstreamDependenciesMojo.java
Labels: enhancement, java

#13 Filtering artifact search for package.json
  src/main/java/io/jenkins/blueocean/maven/plugin/ProcessUpstreamDependenciesMojo.java
Labels: bug

#20 remove commons-io dependency
  pom.xml
Labels: dependencies, java
